"""Purpose: Unit tests for StellarService's display-facing filtering.

Description: Verifies per-frame photometry detection stubs (ids
ending ``:Star_<n>``, generated by VariabilityAnalyzer for every point
source in an imaging session's reference frame -- up to 2000 per
session) are excluded from user-facing listings (get_sources,
get_displayable_stellar_objects) but not from get_stellar_objects
itself, which internal round-trip callers like save_objects still
need in full.
"""

import math
from unittest.mock import MagicMock

import pytest

from astrometricslib import SpectroscopyResult, StellarObject
from backend.services.data.stellar_service import (
    StellarService,
    _has_catalog_magnitude,
    _is_per_frame_photometry_detection,
)


def _summary_of(star: StellarObject) -> dict:
    """Describe a star the way the library's quick region read does.

    Returns
    -------
    summary : `dict`
        The keys ``planning.get_library_star_summaries`` returns, with
        an empty coordinate or magnitude turned into `None` as the
        database column would hold it.
    """

    def number_or_none(value: object) -> float | None:
        return value if isinstance(value, int | float) and not isinstance(value, bool) else None

    return {
        "id": star.id,
        "name": star.name,
        "ra": number_or_none(star.right_ascension),
        "dec": number_or_none(star.declination),
        "targetIds": star.target_ids,
        "hasSpectra": star.has_spectra,
        "hasPhotometry": star.has_photometry,
        "magnitude": number_or_none(star.magnitude),
        "spectralType": star.spectral_type,
    }


def _make_service(stellar_objects=None, planning_sources=None, library_stars=None) -> StellarService:  # ruff: ignore[missing-type-function-argument]
    """Build a StellarService whose library and planning are stand-ins.

    Parameters
    ----------
    stellar_objects : `list` [`StellarObject`], optional
        What the full-record star listing returns.
    planning_sources : `list`, optional
        What ``planning.get_sources`` returns (targets, and stars when
        the SIMBAD catalog is asked for).
    library_stars : `list` [`StellarObject`], optional
        The library stars in view. They reach the service as quick
        summaries, the way the real region read supplies them.

    Returns
    -------
    service : `StellarService`
        A service wired to mock astrometrics and wayfinder objects.
    """
    astrometrics = MagicMock()
    astrometrics.stars.list_objects.return_value = stellar_objects or []
    astrometrics.targets.list.return_value = []

    wayfinder = MagicMock()
    wayfinder.planning.get_sources.return_value = planning_sources or []
    wayfinder.planning.get_library_star_summaries.return_value = [
        _summary_of(star) for star in library_stars or []
    ]

    return StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=wayfinder)


def test_is_per_frame_photometry_detection_matches_generated_ids():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify the id pattern VariabilityAnalyzer generates is recognized."""
    assert _is_per_frame_photometry_detection("M 81:2026-01-14:0:0:Star_60") is True
    assert _is_per_frame_photometry_detection("M 81:2026-01-14:0:0:Star_1") is True


def test_is_per_frame_photometry_detection_does_not_match_real_names():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify ordinary catalog/target ids are never mistaken for detections."""
    assert _is_per_frame_photometry_detection("M 81") is False
    assert _is_per_frame_photometry_detection("Polaris") is False
    assert _is_per_frame_photometry_detection("My Custom Star_1") is False  # no colon before "Star_"


def test_get_displayable_stellar_objects_excludes_per_frame_detections():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify the display-facing listing drops VariabilityAnalyzer stubs."""
    catalog_star = StellarObject(id="Polaris", ra=37.95, dec=89.26)
    detection = StellarObject(id="M 81:2026-01-14:0:0:Star_60", ra=148.9, dec=69.0)

    service = _make_service(stellar_objects=[catalog_star, detection])

    displayable = service.get_displayable_stellar_objects()
    assert [obj.id for obj in displayable] == ["Polaris"]

    # get_stellar_objects itself must still return both -- internal callers
    # like save_objects()/find_or_create_by_position() round-trip the full set.
    assert [obj.id for obj in service.get_stellar_objects()] == ["Polaris", "M 81:2026-01-14:0:0:Star_60"]


def test_get_sources_excludes_per_frame_detections_with_real_coordinates():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify get_sources() drops solved (coordinate-bearing) detection stubs.

    Regression test: an earlier filter only caught pre-WCS-solve stubs
    (which lack ra/dec entirely); once a session is plate-solved these
    detections get real sky coordinates and slipped through into the
    Planetarium's star field as if they were catalog stars.
    """
    catalog_star = StellarObject(id="Polaris", ra=37.95, dec=89.26, magnitude=2.0)
    solved_detection = StellarObject(id="M 81:2026-01-14:0:0:Star_60", ra=148.9, dec=69.0)
    unsolved_detection = StellarObject(id="M 81:2026-01-14:0:0:Star_61", ra="", dec="")

    service = _make_service(
        library_stars=[catalog_star, solved_detection, unsolved_detection],
    )

    sources = service.get_sources(ra=148.9, dec=69.0, radius=2.5)
    assert [source["id"] for source in sources] == ["Polaris"]


def test_get_sources_uses_camel_case_keys_the_planetarium_reads():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify source payloads use camelCase data-flag and spectral-type keys.

    Regression test: ``hasSpectra``, ``hasPhotometry`` and ``spectralType``
    were once sent in snake_case while the Planetarium's PlanetariumSource
    type and info card read camelCase, so a star clicked on the sky map
    always looked like it had no data and its plot checkboxes and "Open in
    Astronomy Manager" never showed.
    """
    star_with_photometry = StellarObject(
        id="2MASS J16430250+3643212",
        ra=250.76,
        dec=36.72,
        spectral_type="K2",
        photometry={"timestamps": ["2026-01-01T00:00:00Z"], "magnitudes": [0.5]},
    )
    star_without_data = StellarObject(id="Polaris", ra=37.95, dec=89.26)

    service = _make_service(library_stars=[star_with_photometry, star_without_data])

    sources = {source["id"]: source for source in service.get_sources(ra=250.76, dec=36.72, radius=2.5)}

    with_data = sources["2MASS J16430250+3643212"]
    assert with_data["hasPhotometry"] is True
    assert with_data["hasSpectra"] is False
    assert with_data["spectralType"] == "K2"

    without_data = sources["Polaris"]
    assert without_data["hasPhotometry"] is False
    assert without_data["hasSpectra"] is False

    for source in sources.values():
        assert "has_spectra" not in source
        assert "has_photometry" not in source
        assert "spectral_type" not in source


def test_get_online_catalog_sources_passes_the_limiting_magnitude_to_the_drivers():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify the map's limiting magnitude reaches the catalog drivers.

    The deep-star (Gaia) layer only needs stars the map can draw at the
    current zoom, so the UI's limit must travel down to the driver that
    builds the query.
    """
    service = _make_service()
    service.wayfinder.planning.get_online_catalog_sources.return_value = []

    service.get_online_catalog_sources(
        ra=250.0, dec=36.0, radius=2.0, enabled_drivers=["gaia"], limiting_magnitude=14.0
    )

    service.wayfinder.planning.get_online_catalog_sources.assert_called_once_with(
        ra_deg=250.0,
        dec_deg=36.0,
        radius_deg=2.0,
        enabled_driver_names=["gaia"],
        magnitude_limit=14.0,
    )


def test_get_online_catalog_sources_limit_is_optional():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify callers sending no limit (e.g. Hipparcos) still work."""
    service = _make_service()
    service.wayfinder.planning.get_online_catalog_sources.return_value = []

    service.get_online_catalog_sources(ra=0.0, dec=0.0, radius=180.0, enabled_drivers=["hipparcos"])

    assert service.wayfinder.planning.get_online_catalog_sources.call_args.kwargs["magnitude_limit"] is None


def test_get_deep_catalog_status_adds_the_install_command():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify the status the UI sees names the command that downloads it."""
    from backend.services.data.stellar_service import DEEP_CATALOG_INSTALL_COMMAND

    service = _make_service()
    service.astrometrics.stars.get_deep_catalog_status.return_value = {
        "installed": False,
        "complete": False,
        "star_count": 0,
    }

    status = service.get_deep_catalog_status()

    assert status["installed"] is False
    assert status["installCommand"] == DEEP_CATALOG_INSTALL_COMMAND
    assert "build_deep_star_catalog" in status["installCommand"]


def test_stellar_object_has_spectra_and_has_photometry_computed_fields():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify StellarObject hasSpectra/hasPhotometry fields in model dump.

    Ensures that when StellarObject is serialized to JSON for RPC responses,
    hasSpectra and hasPhotometry computed properties are present and
    accurately reflect the presence of spectra or light curve photometry
    data.
    """
    star_with_spectra = StellarObject(
        id="Vega",
        spectroscopy=SpectroscopyResult(wavelengths_angstrom=[5000], intensities=[1.0]),
    )
    star_with_photometry = StellarObject(
        id="Betelgeuse",
        photometry={"timestamps": ["2026-01-01T00:00:00Z"], "magnitudes": [0.5]},
    )
    star_empty = StellarObject(id="EmptyStar")

    assert star_with_spectra.has_spectra is True
    assert star_with_spectra.has_photometry is False

    assert star_with_photometry.has_spectra is False
    assert star_with_photometry.has_photometry is True

    assert star_empty.has_spectra is False
    assert star_empty.has_photometry is False

    # Check serialized dictionary (by_alias=True)
    dumped = star_with_spectra.model_dump(by_alias=True)
    assert dumped["hasSpectra"] is True
    assert dumped["hasPhotometry"] is False
    assert dumped["plotData"] == {"wavelengths": [5000.0], "intensities": [1.0]}

    # Check RPC serialization
    from backend.services.rpc_protocol import serialize_rpc_result

    rpc_data = serialize_rpc_result(star_with_spectra)
    assert rpc_data["hasSpectra"] is True
    assert rpc_data["plotData"] == {"wavelengths": [5000.0], "intensities": [1.0]}


def test_get_displayable_stellar_object_summaries_excludes_per_frame_detections(tmp_path):  # ruff: ignore[missing-type-function-argument, missing-return-type-undocumented-public-function]
    """Verify the lightweight summary listing also drops detection stubs.

    Mirrors test_get_displayable_stellar_objects_excludes_per_frame_detections
    for get_displayable_stellar_object_summaries, the path astronomy:list
    actually uses -- built on StellarCatalog.list_object_summaries's
    disk-backed lightweight read rather than a fully-hydrated
    StellarObject list, so the per-frame-stub filter needs its own
    coverage against that path. Uses a real Astrometrics (not a
    MagicMock) since the point is exercising the actual disk-backed
    summary read, not a mocked stand-in for it.
    """
    import json
    import sqlite3

    from astrometricslib import AppConfiguration, Astrometrics

    library_path = tmp_path / "library"
    (library_path / "targets").mkdir(parents=True)
    (library_path / "frames").mkdir(parents=True)
    config = AppConfiguration()
    config.update_config({
        "Image Library": {"path": str(library_path), "frames_path": str(library_path / "frames")}
    })

    db_path = str(library_path / "astrometrics.db")
    conn = sqlite3.connect(db_path)
    conn.execute(
        """
        CREATE TABLE stellar_objects (
            id TEXT PRIMARY KEY, target_id TEXT, name TEXT,
            ra REAL, dec REAL, magnitude REAL, data_json TEXT
        )
        """
    )
    conn.execute(
        "INSERT INTO stellar_objects (id, data_json) VALUES (?, ?)",
        ("Polaris", json.dumps({"id": "Polaris", "name": "Polaris", "targetIds": []})),
    )
    conn.execute(
        "INSERT INTO stellar_objects (id, data_json) VALUES (?, ?)",
        (
            "M 81:2026-01-14:0:0:Star_60",
            json.dumps({"id": "M 81:2026-01-14:0:0:Star_60", "name": "detection", "targetIds": ["M 81"]}),
        ),
    )
    conn.commit()
    conn.close()

    service = StellarService(config=config, astrometrics=Astrometrics(config=config), wayfinder=MagicMock())
    summaries = service.get_displayable_stellar_object_summaries()

    assert [s["id"] for s in summaries] == ["Polaris"]


def test_get_displayable_stellar_object_summaries_limits_to_100_by_default() -> None:
    """Verify that get_displayable_stellar_object_summaries defaults to 100.

    Ensures that when more than 100 stars are in the catalog, only the first
    100 displayable stars are returned to prevent UI loading bottlenecks.
    """
    mock_stars = [
        {"id": f"Star_{i:03d}_Real", "name": f"Catalog Star {i}", "hasSpectra": False, "hasPhotometry": False}
        for i in range(250)
    ]
    astrometrics = MagicMock()
    astrometrics.stars.list_object_summaries.return_value = mock_stars
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())

    summaries = service.get_displayable_stellar_object_summaries()
    assert len(summaries) == 100
    assert summaries[0]["id"] == "Star_000_Real"
    assert summaries[99]["id"] == "Star_099_Real"


def test_get_displayable_stellar_object_summaries_searches_across_all_records() -> None:
    """Verify that search filters evaluate against the full catalog.

    Ensures that an object located past index 100 in the catalog (e.g. index
    150) is found and returned when matching the search query, rather than
    only searching within an already-truncated 100 item slice.
    """
    mock_stars = [
        {"id": f"Star_{i:03d}_Real", "name": f"Catalog Star {i}", "hasSpectra": False, "hasPhotometry": False}
        for i in range(200)
    ]
    mock_stars.append({
        "id": "HD_99999",
        "name": "Target Star Alpha",
        "hasSpectra": True,
        "hasPhotometry": True,
    })
    astrometrics = MagicMock()
    astrometrics.stars.list_object_summaries.return_value = mock_stars
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())

    # Search for star at the end of the 200+ list
    results = service.get_displayable_stellar_object_summaries(search="Target Star")
    assert len(results) == 1
    assert results[0]["id"] == "HD_99999"

    # Search by ID substring
    results_by_id = service.get_displayable_stellar_object_summaries(search="99999")
    assert len(results_by_id) == 1
    assert results_by_id[0]["id"] == "HD_99999"


def test_get_displayable_stellar_object_summaries_search_disables_the_summary_cap() -> None:
    """Verify a search request asks for every row, not a capped slice.

    The test above (searches_across_all_records) mocks
    list_object_summaries to always return every row regardless of what
    it was asked for, so it cannot catch list_object_summaries itself
    silently capping the real, un-mocked catalog at
    DEFAULT_UNFILTERED_SUMMARY_LIMIT (5000) rows before this function's
    own search filtering ever runs -- a real match past that cutoff
    would then never be found. This checks the actual call contract
    instead: a search request must pass apply_default_limit=False.
    """
    astrometrics = MagicMock()
    astrometrics.stars.list_object_summaries.return_value = []
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())

    service.get_displayable_stellar_object_summaries(search="Target Star")
    astrometrics.stars.list_object_summaries.assert_called_once_with(None, None, apply_default_limit=False)

    astrometrics.stars.list_object_summaries.reset_mock()
    service.get_displayable_stellar_object_summaries(filter_type="With Spectra")
    astrometrics.stars.list_object_summaries.assert_called_once_with(None, None, apply_default_limit=False)

    astrometrics.stars.list_object_summaries.reset_mock()
    service.get_displayable_stellar_object_summaries(offset=100)
    astrometrics.stars.list_object_summaries.assert_called_once_with(None, None, apply_default_limit=False)

    # A plain unfiltered request still uses the default cap.
    astrometrics.stars.list_object_summaries.reset_mock()
    service.get_displayable_stellar_object_summaries()
    astrometrics.stars.list_object_summaries.assert_called_once_with(None, 100, apply_default_limit=True)


def test_get_displayable_stellar_object_summaries_category_filters() -> None:
    """Verify that category filtering filters across catalog and limits count.

    Ensures that filter_type='With Spectra' and filter_type='With Photometry'
    only return stars matching the respective capability flag.
    """
    mock_stars = [
        {"id": "Star_Spectra_1", "name": "Spec 1", "hasSpectra": True, "hasPhotometry": False},
        {"id": "Star_Phot_1", "name": "Phot 1", "hasSpectra": False, "hasPhotometry": True},
        {"id": "Star_Both_1", "name": "Both 1", "hasSpectra": True, "hasPhotometry": True},
        {"id": "Star_None_1", "name": "None 1", "hasSpectra": False, "hasPhotometry": False},
    ]
    astrometrics = MagicMock()
    astrometrics.stars.list_object_summaries.return_value = mock_stars
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())

    spectra_results = service.get_displayable_stellar_object_summaries(filter_type="With Spectra")
    # A filtered listing is sorted, and a star with photometry as well as a
    # spectrum comes before one with only a spectrum.
    assert [s["id"] for s in spectra_results] == ["Star_Both_1", "Star_Spectra_1"]

    phot_results = service.get_displayable_stellar_object_summaries(filter_type="With Photometry")
    assert [s["id"] for s in phot_results] == ["Star_Both_1", "Star_Phot_1"]


def test_get_displayable_stellar_object_summaries_offset_pagination() -> None:
    """Verify that offset pagination skips items appropriately."""
    mock_stars = [
        {"id": f"HD_{i:03d}", "name": f"Star {i}", "hasSpectra": True, "hasPhotometry": True}
        for i in range(250)
    ]
    astrometrics = MagicMock()
    astrometrics.stars.list_object_summaries.return_value = mock_stars
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())

    page_1 = service.get_displayable_stellar_object_summaries(limit=100, offset=0)
    assert len(page_1) == 100
    assert page_1[0]["id"] == "HD_000"
    assert page_1[99]["id"] == "HD_099"

    page_2 = service.get_displayable_stellar_object_summaries(limit=100, offset=100)
    assert len(page_2) == 100
    assert page_2[0]["id"] == "HD_100"
    assert page_2[99]["id"] == "HD_199"

    page_3 = service.get_displayable_stellar_object_summaries(limit=100, offset=200)
    assert len(page_3) == 50
    assert page_3[0]["id"] == "HD_200"
    assert page_3[49]["id"] == "HD_249"


def test_has_catalog_magnitude_rejects_missing_and_instrumental_values():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify only real apparent magnitudes count as catalog magnitudes."""
    assert _has_catalog_magnitude(0.03) is True
    assert _has_catalog_magnitude(-1.46) is True  # Sirius
    assert _has_catalog_magnitude(14) is True
    assert _has_catalog_magnitude("") is False
    assert _has_catalog_magnitude(None) is False
    assert _has_catalog_magnitude(-14.98) is False  # instrumental photometry
    assert _has_catalog_magnitude(float("nan")) is False
    assert _has_catalog_magnitude(True) is False
    # Exactly 0 is what is saved when the catalog gave no magnitude; a real
    # star (Vega, 0.03) is not exactly 0.
    assert _has_catalog_magnitude(0) is False
    assert _has_catalog_magnitude(0.0) is False


def test_get_sources_thins_faint_and_uncataloged_stars():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify limiting_magnitude and the uncataloged-stars flag trim results.

    A wide-FOV Planetarium view can match hundreds of thousands of local
    stars, most of them per-field detections whose magnitude is empty or
    instrumental, so a magnitude cut alone can't thin them out.
    """
    bright_star = StellarObject(id="Bright", ra=10.0, dec=10.0, magnitude=3.0)
    faint_star = StellarObject(id="Faint", ra=10.1, dec=10.1, magnitude=14.0)
    empty_magnitude_star = StellarObject(id="EmptyMagnitude", ra=10.2, dec=10.2, magnitude="")
    unknown_magnitude_star = StellarObject(id="NoMagnitude", ra=10.3, dec=10.3)
    instrumental_star = StellarObject(id="Instrumental", ra=10.4, dec=10.4, magnitude=-14.9)

    service = _make_service(
        library_stars=[
            bright_star,
            faint_star,
            empty_magnitude_star,
            unknown_magnitude_star,
            instrumental_star,
        ],
    )

    def returned_ids(**filters: float | bool) -> list[str]:
        return [source["id"] for source in service.get_sources(ra=10.0, dec=10.0, radius=5.0, **filters)]

    assert returned_ids() == ["Bright", "Faint", "EmptyMagnitude", "NoMagnitude", "Instrumental"]

    assert returned_ids(limiting_magnitude=6.0) == [
        "Bright",
        "EmptyMagnitude",
        "NoMagnitude",
        "Instrumental",
    ]

    assert returned_ids(include_stars_without_catalog_magnitude=False) == ["Bright", "Faint"]

    assert returned_ids(limiting_magnitude=6.0, include_stars_without_catalog_magnitude=False) == ["Bright"]


def test_get_sources_reads_stars_from_summaries_and_loads_only_targets():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify the Planetarium path never loads the library's stars in full.

    Loading every star just to check its position took about ten seconds
    on a real library, so the stars must arrive as quick summaries and the
    full-object search must be told to leave them out.
    """
    star = StellarObject(id="Polaris", ra=37.95, dec=89.26, magnitude=2.0)
    service = _make_service(library_stars=[star])

    sources = service.get_sources(ra=37.95, dec=89.26, radius=2.5)

    assert [source["id"] for source in sources] == ["Polaris"]
    service.wayfinder.planning.get_sources.assert_called_once_with(
        37.95, 89.26, 2.5, include_catalog=False, include_stars=False
    )
    service.wayfinder.planning.get_library_star_summaries.assert_called_once_with(37.95, 89.26, 2.5, None)


def test_get_sources_summary_payload_has_the_same_shape_as_a_full_star_payload():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify a star read from a summary is described the same way.

    The Planetarium reads these keys, so the fast path must send exactly
    what the full-object path sends for the same star.
    """
    star = StellarObject(
        id="HD 201684", name="HD 201684", ra=316.8, dec=68.6, magnitude=8.09, spectral_type="B3V"
    )

    summary_source = _make_service(library_stars=[star]).get_sources(ra=316.8, dec=68.6, radius=2.5)[0]
    full_object_source = _make_service(planning_sources=[star]).get_sources(
        ra=316.8, dec=68.6, radius=2.5, include_stars_without_catalog_magnitude=True
    )[0]

    assert summary_source == full_object_source


def test_get_sources_asks_the_library_only_for_catalog_magnitudes_when_uncataloged_stars_are_off():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify the magnitude limit reaches the database as a range.

    A wide view only wants stars with a real catalog magnitude, at or
    below the limit. Asking the database for exactly that keeps it from
    reading tens of thousands of stars the loop would only throw away.
    """
    service = _make_service()

    service.get_sources(
        ra=10.0, dec=10.0, radius=5.0, limiting_magnitude=6.0, include_stars_without_catalog_magnitude=False
    )
    service.get_sources(ra=10.0, dec=10.0, radius=5.0, include_stars_without_catalog_magnitude=False)

    calls = service.wayfinder.planning.get_library_star_summaries.call_args_list
    assert calls[0].args == (10.0, 10.0, 5.0, (-2.0, 6.0))
    assert calls[1].args == (10.0, 10.0, 5.0, (-2.0, math.inf))


def test_get_displayable_stellar_object_summaries_sorts_a_targets_stars_usefully() -> None:
    """Verify a target's stars sort spectra, named, then brightest.

    A position-only ``FIELD_J`` star with an instrumental (very negative)
    magnitude must not sort ahead of a catalog star, and a star with no
    magnitude sorts after every star that has one.
    """
    mock_stars = [
        {"id": "FIELD_J10.0000+20.0000", "hasSpectra": False, "hasPhotometry": True, "magnitude": -16.4},
        {"id": "Gaia DR3 2", "hasSpectra": False, "hasPhotometry": True, "magnitude": 11.0},
        {"id": "Gaia DR3 1", "hasSpectra": False, "hasPhotometry": True, "magnitude": 8.0},
        {"id": "Gaia DR3 3", "hasSpectra": False, "hasPhotometry": True, "magnitude": None},
        {"id": "HD 5", "hasSpectra": True, "hasPhotometry": False, "magnitude": 9.0},
        {"id": "Gaia DR3 4", "hasSpectra": False, "hasPhotometry": False, "magnitude": 5.0},
    ]
    astrometrics = MagicMock()
    astrometrics.stars.list_object_summaries.return_value = mock_stars
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())

    summaries = service.get_displayable_stellar_object_summaries(target_id="M 13")

    assert [summary["id"] for summary in summaries] == [
        "HD 5",
        "Gaia DR3 1",
        "Gaia DR3 2",
        "Gaia DR3 3",
        "Gaia DR3 4",
        "FIELD_J10.0000+20.0000",
    ]
    astrometrics.stars.list_object_summaries.assert_called_once_with("M 13", None, apply_default_limit=False)


def test_get_displayable_stellar_object_summaries_leaves_unfiltered_order_alone() -> None:
    """Verify an unfiltered browse keeps database order for stable pages."""
    mock_stars = [
        {"id": "Gaia DR3 9", "hasSpectra": False, "hasPhotometry": False, "magnitude": 12.0},
        {"id": "Gaia DR3 1", "hasSpectra": True, "hasPhotometry": True, "magnitude": 3.0},
    ]
    astrometrics = MagicMock()
    astrometrics.stars.list_object_summaries.return_value = mock_stars
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())

    summaries = service.get_displayable_stellar_object_summaries()

    assert [summary["id"] for summary in summaries] == ["Gaia DR3 9", "Gaia DR3 1"]


def test_analyze_periodicity_delegates_to_the_stars_api() -> None:
    """Verify the RPC method hands the id to the library."""
    astrometrics = MagicMock()
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())

    result = service.analyze_periodicity("Gaia DR3 1")

    astrometrics.stars.analyze_periodicity.assert_called_once_with("Gaia DR3 1")
    assert result is astrometrics.stars.analyze_periodicity.return_value


@pytest.mark.anyio
async def test_rpc_registry_routes_analyze_periodicity_to_the_stellar_service(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Verify astronomy:analyze_periodicity reaches the stellar service."""
    from backend.routers import rpc_router

    stellar_service = MagicMock()
    monkeypatch.setattr(rpc_router.container, "stellar_service", stellar_service, raising=False)

    registry = rpc_router.RPCHandlerRegistry()
    result = await registry.execute("astronomy:analyze_periodicity", {"object_id": "Gaia DR3 1"})

    stellar_service.analyze_periodicity.assert_called_once_with(object_id="Gaia DR3 1")
    assert result is stellar_service.analyze_periodicity.return_value


def test_period_searches_are_limited_to_two_at_a_time() -> None:
    """Verify a third search waits until one of the first two finishes."""
    import threading

    running = 0
    peak = 0
    lock = threading.Lock()
    release = threading.Event()

    def slow_search(_object_id: str) -> None:
        nonlocal running, peak
        with lock:
            running += 1
            peak = max(peak, running)
        release.wait(timeout=2.0)
        with lock:
            running -= 1

    astrometrics = MagicMock()
    astrometrics.stars.analyze_periodicity.side_effect = slow_search
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())
    threads = [threading.Thread(target=service.analyze_periodicity, args=(f"star {i}",)) for i in range(5)]
    for thread in threads:
        thread.start()
    threading.Event().wait(0.3)
    assert peak == 2
    release.set()
    for thread in threads:
        thread.join(timeout=5.0)
    assert peak == 2
