"""Purpose: Unit tests for StellarService's display-facing filtering.

Description: Verifies per-frame photometry detection stubs (ids
ending ``:Star_<n>``, generated by VariabilityAnalyzer for every point
source in an imaging session's reference frame -- up to 2000 per
session) are excluded from user-facing listings (get_sources,
get_displayable_stellar_objects) but not from get_stellar_objects
itself, which internal round-trip callers like save_objects still
need in full.
"""

from unittest.mock import MagicMock

from astrometricslib import SpectroscopyResult, StellarObject
from backend.services.data.stellar_service import (
    StellarService,
    _has_catalog_magnitude,
    _is_per_frame_photometry_detection,
)


def _make_service(stellar_objects=None, planning_sources=None) -> StellarService:  # ruff: ignore[missing-type-function-argument]
    astrometrics = MagicMock()
    astrometrics.stars.list_objects.return_value = stellar_objects or []
    astrometrics.targets.list.return_value = []

    wayfinder = MagicMock()
    wayfinder.planning.get_sources.return_value = planning_sources or []

    return StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=wayfinder)


def test_is_per_frame_photometry_detection_matches_generated_ids():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify the id pattern VariabilityAnalyzer generates is recognized."""
    assert _is_per_frame_photometry_detection("M 81:2026-01-14:0:0:Star_60") is True
    assert _is_per_frame_photometry_detection("M 81:2026-01-14:0:0:Star_1") is True


def test_is_per_frame_photometry_detection_does_not_match_real_names():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify ordinary catalog/target ids are never mistaken for detections."""
    assert _is_per_frame_photometry_detection("M 81") is False
    assert _is_per_frame_photometry_detection("Polaris") is False
    assert _is_per_frame_photometry_detection("My Custom Star_1") is False  # no colon before "Star_"


def test_get_displayable_stellar_objects_excludes_per_frame_detections():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify the display-facing listing drops VariabilityAnalyzer stubs."""
    catalog_star = StellarObject(id="Polaris", ra=37.95, dec=89.26)
    detection = StellarObject(id="M 81:2026-01-14:0:0:Star_60", ra=148.9, dec=69.0)

    service = _make_service(stellar_objects=[catalog_star, detection])

    displayable = service.get_displayable_stellar_objects()
    assert [obj.id for obj in displayable] == ["Polaris"]

    # get_stellar_objects itself must still return both -- internal callers
    # like save_objects()/find_or_create_by_position() round-trip the full set.
    assert [obj.id for obj in service.get_stellar_objects()] == ["Polaris", "M 81:2026-01-14:0:0:Star_60"]


def test_get_sources_excludes_per_frame_detections_with_real_coordinates():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify get_sources() drops solved (coordinate-bearing) detection stubs.

    Regression test: an earlier filter only caught pre-WCS-solve stubs
    (which lack ra/dec entirely); once a session is plate-solved these
    detections get real sky coordinates and slipped through into the
    Planetarium's star field as if they were catalog stars.
    """
    catalog_star = StellarObject(id="Polaris", ra=37.95, dec=89.26, magnitude=2.0)
    solved_detection = StellarObject(id="M 81:2026-01-14:0:0:Star_60", ra=148.9, dec=69.0)
    unsolved_detection = StellarObject(id="M 81:2026-01-14:0:0:Star_61", ra="", dec="")

    service = _make_service(
        planning_sources=[catalog_star, solved_detection, unsolved_detection],
    )

    sources = service.get_sources(ra=148.9, dec=69.0, radius=2.5)
    assert [source["id"] for source in sources] == ["Polaris"]


def test_get_sources_uses_camel_case_keys_the_planetarium_reads():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify source payloads use camelCase data-flag and spectral-type keys.

    Regression test: ``hasSpectra``, ``hasPhotometry`` and ``spectralType``
    were once sent in snake_case while the Planetarium's PlanetariumSource
    type and info card read camelCase, so a star clicked on the sky map
    always looked like it had no data and its plot checkboxes and "Open in
    Astronomy Manager" never showed.
    """
    star_with_photometry = StellarObject(
        id="2MASS J16430250+3643212",
        ra=250.76,
        dec=36.72,
        spectral_type="K2",
        photometry={"timestamps": ["2026-01-01T00:00:00Z"], "magnitudes": [0.5]},
    )
    star_without_data = StellarObject(id="Polaris", ra=37.95, dec=89.26)

    service = _make_service(planning_sources=[star_with_photometry, star_without_data])

    sources = {source["id"]: source for source in service.get_sources(ra=250.76, dec=36.72, radius=2.5)}

    with_data = sources["2MASS J16430250+3643212"]
    assert with_data["hasPhotometry"] is True
    assert with_data["hasSpectra"] is False
    assert with_data["spectralType"] == "K2"

    without_data = sources["Polaris"]
    assert without_data["hasPhotometry"] is False
    assert without_data["hasSpectra"] is False

    for source in sources.values():
        assert "has_spectra" not in source
        assert "has_photometry" not in source
        assert "spectral_type" not in source


def test_stellar_object_has_spectra_and_has_photometry_computed_fields():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify StellarObject hasSpectra/hasPhotometry fields in model dump.

    Ensures that when StellarObject is serialized to JSON for RPC responses,
    hasSpectra and hasPhotometry computed properties are present and
    accurately reflect the presence of spectra or light curve photometry
    data.
    """
    star_with_spectra = StellarObject(
        id="Vega",
        spectroscopy=SpectroscopyResult(wavelengths_angstrom=[5000], intensities=[1.0]),
    )
    star_with_photometry = StellarObject(
        id="Betelgeuse",
        photometry={"timestamps": ["2026-01-01T00:00:00Z"], "magnitudes": [0.5]},
    )
    star_empty = StellarObject(id="EmptyStar")

    assert star_with_spectra.has_spectra is True
    assert star_with_spectra.has_photometry is False

    assert star_with_photometry.has_spectra is False
    assert star_with_photometry.has_photometry is True

    assert star_empty.has_spectra is False
    assert star_empty.has_photometry is False

    # Check serialized dictionary (by_alias=True)
    dumped = star_with_spectra.model_dump(by_alias=True)
    assert dumped["hasSpectra"] is True
    assert dumped["hasPhotometry"] is False
    assert dumped["plotData"] == {"wavelengths": [5000.0], "intensities": [1.0]}

    # Check RPC serialization
    from backend.services.rpc_protocol import serialize_rpc_result

    rpc_data = serialize_rpc_result(star_with_spectra)
    assert rpc_data["hasSpectra"] is True
    assert rpc_data["plotData"] == {"wavelengths": [5000.0], "intensities": [1.0]}


def test_get_displayable_stellar_object_summaries_excludes_per_frame_detections(tmp_path):  # ruff: ignore[missing-type-function-argument, missing-return-type-undocumented-public-function]
    """Verify the lightweight summary listing also drops detection stubs.

    Mirrors test_get_displayable_stellar_objects_excludes_per_frame_detections
    for get_displayable_stellar_object_summaries, the path astronomy:list
    actually uses -- built on StellarCatalog.list_object_summaries's
    disk-backed lightweight read rather than a fully-hydrated
    StellarObject list, so the per-frame-stub filter needs its own
    coverage against that path. Uses a real Astrometrics (not a
    MagicMock) since the point is exercising the actual disk-backed
    summary read, not a mocked stand-in for it.
    """
    import json
    import sqlite3

    from astrometricslib import AppConfiguration, Astrometrics

    library_path = tmp_path / "library"
    (library_path / "targets").mkdir(parents=True)
    (library_path / "frames").mkdir(parents=True)
    config = AppConfiguration()
    config.update_config({
        "Image Library": {"path": str(library_path), "frames_path": str(library_path / "frames")}
    })

    db_path = str(library_path / "astrometrics.db")
    conn = sqlite3.connect(db_path)
    conn.execute(
        """
        CREATE TABLE stellar_objects (
            id TEXT PRIMARY KEY, target_id TEXT, name TEXT,
            ra REAL, dec REAL, magnitude REAL, data_json TEXT
        )
        """
    )
    conn.execute(
        "INSERT INTO stellar_objects (id, data_json) VALUES (?, ?)",
        ("Polaris", json.dumps({"id": "Polaris", "name": "Polaris", "targetIds": []})),
    )
    conn.execute(
        "INSERT INTO stellar_objects (id, data_json) VALUES (?, ?)",
        (
            "M 81:2026-01-14:0:0:Star_60",
            json.dumps({"id": "M 81:2026-01-14:0:0:Star_60", "name": "detection", "targetIds": ["M 81"]}),
        ),
    )
    conn.commit()
    conn.close()

    service = StellarService(config=config, astrometrics=Astrometrics(config=config), wayfinder=MagicMock())
    summaries = service.get_displayable_stellar_object_summaries()

    assert [s["id"] for s in summaries] == ["Polaris"]


def test_get_displayable_stellar_object_summaries_limits_to_100_by_default() -> None:
    """Verify that get_displayable_stellar_object_summaries defaults to 100.

    Ensures that when more than 100 stars are in the catalog, only the first
    100 displayable stars are returned to prevent UI loading bottlenecks.
    """
    mock_stars = [
        {"id": f"Star_{i:03d}_Real", "name": f"Catalog Star {i}", "hasSpectra": False, "hasPhotometry": False}
        for i in range(250)
    ]
    astrometrics = MagicMock()
    astrometrics.stars.list_object_summaries.return_value = mock_stars
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())

    summaries = service.get_displayable_stellar_object_summaries()
    assert len(summaries) == 100
    assert summaries[0]["id"] == "Star_000_Real"
    assert summaries[99]["id"] == "Star_099_Real"


def test_get_displayable_stellar_object_summaries_searches_across_all_records() -> None:
    """Verify that search filters evaluate against the full catalog.

    Ensures that an object located past index 100 in the catalog (e.g. index
    150) is found and returned when matching the search query, rather than
    only searching within an already-truncated 100 item slice.
    """
    mock_stars = [
        {"id": f"Star_{i:03d}_Real", "name": f"Catalog Star {i}", "hasSpectra": False, "hasPhotometry": False}
        for i in range(200)
    ]
    mock_stars.append({
        "id": "HD_99999",
        "name": "Target Star Alpha",
        "hasSpectra": True,
        "hasPhotometry": True,
    })
    astrometrics = MagicMock()
    astrometrics.stars.list_object_summaries.return_value = mock_stars
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())

    # Search for star at the end of the 200+ list
    results = service.get_displayable_stellar_object_summaries(search="Target Star")
    assert len(results) == 1
    assert results[0]["id"] == "HD_99999"

    # Search by ID substring
    results_by_id = service.get_displayable_stellar_object_summaries(search="99999")
    assert len(results_by_id) == 1
    assert results_by_id[0]["id"] == "HD_99999"


def test_get_displayable_stellar_object_summaries_search_disables_the_summary_cap() -> None:
    """Verify a search request asks for every row, not a capped slice.

    The test above (searches_across_all_records) mocks
    list_object_summaries to always return every row regardless of what
    it was asked for, so it cannot catch list_object_summaries itself
    silently capping the real, un-mocked catalog at
    DEFAULT_UNFILTERED_SUMMARY_LIMIT (5000) rows before this function's
    own search filtering ever runs -- a real match past that cutoff
    would then never be found. This checks the actual call contract
    instead: a search request must pass apply_default_limit=False.
    """
    astrometrics = MagicMock()
    astrometrics.stars.list_object_summaries.return_value = []
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())

    service.get_displayable_stellar_object_summaries(search="Target Star")
    astrometrics.stars.list_object_summaries.assert_called_once_with(None, None, apply_default_limit=False)

    astrometrics.stars.list_object_summaries.reset_mock()
    service.get_displayable_stellar_object_summaries(filter_type="With Spectra")
    astrometrics.stars.list_object_summaries.assert_called_once_with(None, None, apply_default_limit=False)

    astrometrics.stars.list_object_summaries.reset_mock()
    service.get_displayable_stellar_object_summaries(offset=100)
    astrometrics.stars.list_object_summaries.assert_called_once_with(None, None, apply_default_limit=False)

    # A plain unfiltered request still uses the default cap.
    astrometrics.stars.list_object_summaries.reset_mock()
    service.get_displayable_stellar_object_summaries()
    astrometrics.stars.list_object_summaries.assert_called_once_with(None, 100, apply_default_limit=True)


def test_get_displayable_stellar_object_summaries_category_filters() -> None:
    """Verify that category filtering filters across catalog and limits count.

    Ensures that filter_type='With Spectra' and filter_type='With Photometry'
    only return stars matching the respective capability flag.
    """
    mock_stars = [
        {"id": "Star_Spectra_1", "name": "Spec 1", "hasSpectra": True, "hasPhotometry": False},
        {"id": "Star_Phot_1", "name": "Phot 1", "hasSpectra": False, "hasPhotometry": True},
        {"id": "Star_Both_1", "name": "Both 1", "hasSpectra": True, "hasPhotometry": True},
        {"id": "Star_None_1", "name": "None 1", "hasSpectra": False, "hasPhotometry": False},
    ]
    astrometrics = MagicMock()
    astrometrics.stars.list_object_summaries.return_value = mock_stars
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())

    spectra_results = service.get_displayable_stellar_object_summaries(filter_type="With Spectra")
    assert [s["id"] for s in spectra_results] == ["Star_Spectra_1", "Star_Both_1"]

    phot_results = service.get_displayable_stellar_object_summaries(filter_type="With Photometry")
    assert [s["id"] for s in phot_results] == ["Star_Phot_1", "Star_Both_1"]


def test_get_displayable_stellar_object_summaries_offset_pagination() -> None:
    """Verify that offset pagination skips items appropriately."""
    mock_stars = [
        {"id": f"HD_{i:03d}", "name": f"Star {i}", "hasSpectra": True, "hasPhotometry": True}
        for i in range(250)
    ]
    astrometrics = MagicMock()
    astrometrics.stars.list_object_summaries.return_value = mock_stars
    service = StellarService(config=MagicMock(), astrometrics=astrometrics, wayfinder=MagicMock())

    page_1 = service.get_displayable_stellar_object_summaries(limit=100, offset=0)
    assert len(page_1) == 100
    assert page_1[0]["id"] == "HD_000"
    assert page_1[99]["id"] == "HD_099"

    page_2 = service.get_displayable_stellar_object_summaries(limit=100, offset=100)
    assert len(page_2) == 100
    assert page_2[0]["id"] == "HD_100"
    assert page_2[99]["id"] == "HD_199"

    page_3 = service.get_displayable_stellar_object_summaries(limit=100, offset=200)
    assert len(page_3) == 50
    assert page_3[0]["id"] == "HD_200"
    assert page_3[49]["id"] == "HD_249"


def test_has_catalog_magnitude_rejects_missing_and_instrumental_values():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify only real apparent magnitudes count as catalog magnitudes."""
    assert _has_catalog_magnitude(0.03) is True
    assert _has_catalog_magnitude(-1.46) is True  # Sirius
    assert _has_catalog_magnitude(14) is True
    assert _has_catalog_magnitude("") is False
    assert _has_catalog_magnitude(None) is False
    assert _has_catalog_magnitude(-14.98) is False  # instrumental photometry
    assert _has_catalog_magnitude(float("nan")) is False
    assert _has_catalog_magnitude(True) is False


def test_get_sources_thins_faint_and_uncataloged_stars():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify limiting_magnitude and the uncataloged-stars flag trim results.

    A wide-FOV Planetarium view can match hundreds of thousands of local
    stars, most of them per-field detections whose magnitude is empty or
    instrumental, so a magnitude cut alone can't thin them out.
    """
    bright_star = StellarObject(id="Bright", ra=10.0, dec=10.0, magnitude=3.0)
    faint_star = StellarObject(id="Faint", ra=10.1, dec=10.1, magnitude=14.0)
    empty_magnitude_star = StellarObject(id="EmptyMagnitude", ra=10.2, dec=10.2, magnitude="")
    unknown_magnitude_star = StellarObject(id="NoMagnitude", ra=10.3, dec=10.3)
    instrumental_star = StellarObject(id="Instrumental", ra=10.4, dec=10.4, magnitude=-14.9)

    service = _make_service(
        planning_sources=[
            bright_star,
            faint_star,
            empty_magnitude_star,
            unknown_magnitude_star,
            instrumental_star,
        ],
    )

    def returned_ids(**filters: float | bool) -> list[str]:
        return [source["id"] for source in service.get_sources(ra=10.0, dec=10.0, radius=5.0, **filters)]

    assert returned_ids() == ["Bright", "Faint", "EmptyMagnitude", "NoMagnitude", "Instrumental"]

    assert returned_ids(limiting_magnitude=6.0) == [
        "Bright",
        "EmptyMagnitude",
        "NoMagnitude",
        "Instrumental",
    ]

    assert returned_ids(include_stars_without_catalog_magnitude=False) == ["Bright", "Faint"]

    assert returned_ids(limiting_magnitude=6.0, include_stars_without_catalog_magnitude=False) == ["Bright"]
