/**
 * Purpose: The MCP tool profile rules for the UI MCP server.
 *
 * Generated by build/mcp/generate_client_configs.py from mcp_servers/common/profile.py.
 * Do not edit by hand. Change the Python file and run the generator again.
 */

/** Environment variable that chooses the profile when the server starts. */
export const PROFILE_ENVIRONMENT_VARIABLE = "ASTROMETRICS_MCP_PROFILE";

/** The profile used when the variable is unset or not recognized. */
export const DEFAULT_PROFILE = "investigator";

/** Profile name -> the tool classes it may use. */
export const PROFILE_CLASSES: Readonly<Record<string, ReadonlySet<string>>> = {
  investigator: new Set(["compute", "ingest", "observe", "process", "ui-control"]),
  developer: new Set(["compute", "develop", "ingest", "observe", "process", "ui-control"]),
};

/** Dispositions a client may use. */
export const SERVED_DISPOSITIONS: ReadonlySet<string> = new Set(["keep", "merge"]);

/** Instructions the server gives its client at the start of a session. */
export const GAP_REPORT_GUIDANCE = "These tools look things up and calculate. The only writes are bringing frames from the telescope into the library and stacking a target's frames the way the app does. If none of the tools you can use can do what you need, stop. Do not look for a workaround: do not chain tools to imitate a missing one, and do not ask for code to be run. Call report_capability_gap on the astrometrics-gaps server. Say what you tried, why it fell short, and what tool would help. Then tell the person you cannot do it with the current tools.";

/** A short reminder added to every refusal. */
export const GAP_REPORT_REMINDER = "If you need this ability, stop and file a report with report_capability_gap on the astrometrics-gaps server. Do not look for a workaround.";
