"""Purpose: Unit tests for the geometric pointing model fit/predict pair.

Description: Verifies `fit_pointing_model` recovers known coefficients
from synthetic plate-solve data generated by the exact same forward
model, and that `predict_pointing_error` (added in M7b, sharing
`_pointing_geometry` with the fit) reproduces that synthetic data
exactly -- the fit and predict directions of one geometric model must
never drift apart.
"""

import pytest

from wayfindinglib.analytics.pointing_model import (
    _pointing_geometry,
    fit_pointing_model,
    predict_pointing_error,
)
from wayfindinglib.models.session.telemetry import MountPointingModel

_TRUE_COEFFICIENTS = {"ih": 5.0, "id": -3.0, "me": 20.0, "ma": 10.0, "ch": 2.0, "tf": 1.0}
_LATITUDE_DEG = 40.0


def _synthetic_attempts(positions: list[tuple[float, float]]) -> list[dict[str, float]]:
    """Build plate-solve attempt dicts from the known true coefficients.

    Returns
    -------
    attempts : `list` [`dict`]
        One `{"ra", "dec", "delta_ra_arcsec", "delta_dec_arcsec"}` dict
        per position, generated by evaluating the exact forward model
        this module fits against.
    """
    attempts = []
    for ra, dec in positions:
        g = _pointing_geometry(ra, dec, _LATITUDE_DEG)
        d_ra_cos_dec = (
            -_TRUE_COEFFICIENTS["ih"]
            + _TRUE_COEFFICIENTS["me"] * g["sin_h"] * g["tan_dec"]
            - _TRUE_COEFFICIENTS["ma"] * g["cos_h"] * g["tan_dec"]
            + _TRUE_COEFFICIENTS["ch"] * g["sec_dec"]
            + _TRUE_COEFFICIENTS["tf"] * g["cos_h"] * g["cos_phi"] * g["tan_dec"]
        )
        d_dec = (
            -_TRUE_COEFFICIENTS["id"]
            + _TRUE_COEFFICIENTS["me"] * g["cos_h"]
            + _TRUE_COEFFICIENTS["ma"] * g["sin_h"]
            + _TRUE_COEFFICIENTS["tf"]
            * (g["cos_h"] * g["sin_phi"] * g["sin_dec"] - g["cos_phi"] * g["cos_dec"])
        )
        attempts.append({
            "ra": ra,
            "dec": dec,
            "delta_ra_arcsec": d_ra_cos_dec / g["cos_dec"],
            "delta_dec_arcsec": d_dec,
        })
    return attempts


_POSITIONS = [
    (1.0, 10.0),
    (3.5, -20.0),
    (6.0, 45.0),
    (9.0, -45.0),
    (12.0, 0.0),
    (15.0, 30.0),
    (18.0, -30.0),
    (21.0, 55.0),
    (2.0, -55.0),
    (10.0, 20.0),
]


def test_fit_pointing_model_recovers_known_coefficients_exactly():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify a noiseless synthetic run recovers the true coefficients."""
    model = fit_pointing_model(_synthetic_attempts(_POSITIONS), latitude_deg=_LATITUDE_DEG)

    assert model.ih_arcsec == pytest.approx(_TRUE_COEFFICIENTS["ih"], abs=1e-6)
    assert model.id_arcsec == pytest.approx(_TRUE_COEFFICIENTS["id"], abs=1e-6)
    assert model.me_arcsec == pytest.approx(_TRUE_COEFFICIENTS["me"], abs=1e-6)
    assert model.ma_arcsec == pytest.approx(_TRUE_COEFFICIENTS["ma"], abs=1e-6)
    assert model.ch_arcsec == pytest.approx(_TRUE_COEFFICIENTS["ch"], abs=1e-6)
    assert model.tf_arcsec == pytest.approx(_TRUE_COEFFICIENTS["tf"], abs=1e-6)
    assert model.residual_rms_arcsec == pytest.approx(0.0, abs=1e-6)


def test_predict_pointing_error_reproduces_the_synthetic_input_exactly():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify predict_pointing_error matches the exact forward-model input.

    The fit and predict directions of this one geometric model must
    never drift apart -- if they used different `h`/trig conventions,
    this round trip would fail even with a perfect fit.
    """
    attempts = _synthetic_attempts(_POSITIONS)
    model = fit_pointing_model(attempts, latitude_deg=_LATITUDE_DEG)

    for attempt in attempts:
        predicted_d_ra, predicted_d_dec = predict_pointing_error(
            attempt["ra"], attempt["dec"], model, _LATITUDE_DEG
        )
        assert predicted_d_ra == pytest.approx(attempt["delta_ra_arcsec"], abs=1e-4)
        assert predicted_d_dec == pytest.approx(attempt["delta_dec_arcsec"], abs=1e-4)


def test_predict_pointing_error_is_zero_for_a_zeroed_model():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify a model with every term at its default (0.0) predicts none."""
    zero_model = MountPointingModel(sample_count=0, raw_rms_arcsec=0.0, residual_rms_arcsec=0.0)

    predicted_d_ra, predicted_d_dec = predict_pointing_error(10.0, 20.0, zero_model, _LATITUDE_DEG)

    assert predicted_d_ra == pytest.approx(0.0, abs=1e-9)
    assert predicted_d_dec == pytest.approx(0.0, abs=1e-9)


def test_fit_pointing_model_reports_insufficient_data_below_four_points():  # ruff: ignore[missing-return-type-undocumented-public-function]
    """Verify fewer than 4 valid points short-circuits to insufficient_data."""
    model = fit_pointing_model(_synthetic_attempts(_POSITIONS[:2]), latitude_deg=_LATITUDE_DEG)

    assert model.confidence == "insufficient_data"
    assert model.sample_count == 2
